name: Testes Cypress

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar testes do Cypress
        uses: cypress-io/github-action@v7
        with:
          # Inicia, instala dependências e roda o cypress automaticamente
          install: true